# Generated by Django 5.2.3 on 2025-06-14 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='despesas',
            field=models.TextField(blank=True, help_text='Informações sobre despesas, condomínio e tributos', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_imovel',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero_item',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='address',
            field=models.TextField(blank=True, help_text='Endereço completo do imóvel', null=True),
        ),
    ]
