# Generated by Django 5.2.3 on 2025-06-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imovel_despesas_imovel_numero_imovel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='modalidade',
            field=models.CharField(blank=True, help_text='Modalidade de venda (ex: Leilão, Compra Direta)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor de Avaliação do Imóvel', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor Mínimo de Venda', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='description',
            field=models.TextField(help_text='Descrição principal do imóvel (tipo, área, quartos, etc)'),
        ),
    ]
