# Generated by Django 5.2.3 on 2025-06-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_modalidade_imovel_valor_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='area_privativa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_terreno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='area_total',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='descricao_longa',
            field=models.TextField(blank=True, help_text='Descrição detalhada do imóvel', null=True),
        ),
    ]
