# Generated by Django 5.2.3 on 2025-06-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_imovel_area_privativa_imovel_area_terreno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='descricao_longa',
        ),
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='comarca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_leilao_1',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='data_leilao_2',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='descricao_detalhada',
            field=models.TextField(blank=True, help_text='Descrição longa da página de detalhes', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='edital',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='fotos',
            field=models.JSONField(blank=True, help_text='Lista de URLs das fotos do imóvel', null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='garagem',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='inscricao_imobiliaria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='leiloeiro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='matricula',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='oficio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_venda_leilao_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_venda_leilao_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_privativa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_terreno',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição curta do imóvel', null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='despesas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='modalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='slug',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='source_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_avaliacao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
