# Generated by Django 5.2.3 on 2025-06-21 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imovel',
            name='valor_venda_leilao_1',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='valor_venda_leilao_2',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Valor Mínimo de Venda', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='fotos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='BuscaSalva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_da_busca', models.CharField(help_text='Ex: Apartamentos na Vila Mariana', max_length=100)),
                ('filtros', models.JSONField()),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
