# Generated by Django 5.2.3 on 2025-06-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_remove_imovel_valor_venda_leilao_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='valor_venda_leilao_1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='valor_venda_leilao_2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
