# Generated by Django 5.2.3 on 2025-06-22 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0008_imovel_valor_venda_leilao_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='averbacao_leiloes_negativos',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='link_edital',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='link_matricula',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='site_leiloeiro',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='situacao',
            field=models.CharField(blank=True, help_text='Ex: Ocupado, Desocupado', max_length=100, null=True),
        ),
    ]
