# Generated by Django 5.2.3 on 2025-06-24 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0009_imovel_averbacao_leiloes_negativos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='data_publicacao_edital',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='formas_pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='hdn_imovel_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='regras_despesas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
