# Generated by Django 5.2.3 on 2025-06-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0010_imovel_data_publicacao_edital_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imovel',
            options={'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='despesas',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='imovel',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='imovel',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_privativa',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_terreno',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='area_total',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='averbacao_leiloes_negativos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='cep',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='comarca',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_leilao_1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_leilao_2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='data_publicacao_edital',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='descricao_detalhada',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='edital',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='formas_pagamento',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='fotos',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='garagem',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='hdn_imovel_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='inscricao_imobiliaria',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='leiloeiro',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='link_edital',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='link_matricula',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='matricula',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='modalidade',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero_imovel',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='numero_item',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='oficio',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='quartos',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='regras_despesas',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='site_leiloeiro',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='situacao',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='source_url',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='tipo_imovel',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_avaliacao',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_venda_leilao_1',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='valor_venda_leilao_2',
            field=models.FloatField(null=True),
        ),
    ]
