# Generated by Django 5.2.3 on 2025-06-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0011_alter_imovel_options_remove_imovel_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='link_formas_pagamento',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='link_venda_online',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
