# Generated by Django 5.2.6 on 2025-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0012_imovel_latitude_imovel_link_formas_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(blank=True, db_index=True, max_length=2, null=True),
        ),
    ]
